#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, fileinput, numpy

class Image:
	def __init__(self, matrix=[[]], width=0, height=0, depth=0):
		self.matrix = matrix
		self.width = width
		self.height = height
		self.depth = depth

	def set_width_and_height(self, width, height):
		self.width = width
		self.height = height
		self.matrix = [[0 for j in xrange(height)] for i in xrange(width)]


def write_matrices_to_file(matrixU, matrixS, matrixVt, kmin, kmax, filename, width, height, depth):
	matrixScopy = matrixS.copy()
	if kmax > 0:
		i = 0
		for t in numpy.nditer(matrixScopy, op_flags=['readwrite']):
			if i < kmin or i >= kmax:
				t[...] = 0
			i += 1
	else:
		for t in numpy.nditer(matrixScopy, op_flags=['readwrite']):
			if round(t, 14) <= 0:
				t[...] = 0
	
	A = numpy.dot(numpy.dot(matrixU, numpy.diag(matrixScopy)), matrixVt)

	curMin = 0
	curMax = 0
	for n in numpy.nditer(A):
		if int(round(n)) < curMin:
			curMin = int(round(n))
		if int(round(n)) > curMax:
			curMax = int(round(n))
	if curMax < 255 and curMin < 0:
		shiftVal = 255 - curMax
		for t in numpy.nditer(A, op_flags=['readwrite']):
			t[...] = t + shiftVal
			if t > 255:
				t[...] = 255
			elif t < 0:
				t[...] = 0

	f = open(filename, 'w')
	f.write('P2\n')
	f.write('# Generated by Stoll \n')
	f.write(str(width))
	f.write(' ')
	f.write(str(height))
	f.write('\n')
	f.write(str(depth))
	f.write('\n')
	for n in numpy.nditer(A):
		f.write(str(int(round(n))))
		f.write(' ')
	f.write('\n')
	f.close()


def read_matrix_from_file():
	row = 0
	col = 0
	image = Image()
	for line in fileinput.input():
		if line[0] == '#':
			pass
		elif line[0] == 'P' and line[1] == '2':
			pass
		elif image.width == 0 and image.height == 0:
			x = 0
			y = 0
			x, y = [int(n) for n in line.split()]
			image.set_width_and_height(x, y)
		elif image.depth == 0:
			image.depth = int(line)
		else:
			for value in line.split():
				if col >= len(image.matrix[row]):
					row += 1
					col = 0
				image.matrix[row][col] = value
				col += 1
	return image
	

def process_file():
	image = read_matrix_from_file()

	M = numpy.asmatrix(image.matrix)
	U, s, Vt = numpy.linalg.svd(M, full_matrices=True)
	
	write_matrices_to_file(U, s, Vt, 0, 0, 'out/a_0-0.pgm', image.width, image.height, image.depth)
	write_matrices_to_file(U, s, Vt, 0, 2, 'out/a_0-2.pgm', image.width, image.height, image.depth)
	write_matrices_to_file(U, s, Vt, 0, 4, 'out/a_0-4.pgm', image.width, image.height, image.depth)
	write_matrices_to_file(U, s, Vt, 1, 3, 'out/a_1-3.pgm', image.width, image.height, image.depth)


if __name__ == "__main__":
	if len(sys.argv) >= 2 and sys.argv[1] == "-?":
		print "Syntax: preprocess.py filename.csv"
		print " prints processed file to stdout in csv format"
	else:
		process_file()
